/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('assets/apple/apple.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_apple_01.geometry} material={materials.food_apple_01} />
    </group>
  )
}

useGLTF.preload('assets/apple/apple.gltf')
